services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=256M
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bapi-net

  wordpress:
    image: wordpress:6.8.3-php8.2-apache
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - bapi-net

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    restart: "no"
    networks:
      - bapi-net

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["wp"]
    networks:
      - bapi-net

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - bapi-net

  redis:
    image: redis:7
    restart: "no"
    networks:
      - bapi-net

volumes:
  db_data:

networks:
  bapi-net:
    driver: bridge