version: "3.8"
services:
  wordpress-fpm:
    image: wordpress:6.8.3-php8.2-fpm
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - bapi-net

  nginx:
    image: nginx:stable
    restart: always
    depends_on:
      - wordpress-fpm
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bapi-net

networks:
  bapi-net:
    external: true